/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mdsplus
 */
public class ARDUINO_MUXSetup extends DeviceSetup {

    /**
     * Creates new form ARDUINO_MUXSetup
     */
    public ARDUINO_MUXSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();
        deviceChoice1 = new DeviceChoice();
        jPanel4 = new javax.swing.JPanel();
        deviceField2 = new DeviceField();
        deviceField3 = new DeviceField();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        deviceField4 = new DeviceField();
        deviceField5 = new DeviceField();
        deviceField6 = new DeviceField();
        deviceChoice2 = new DeviceChoice();
        jPanel8 = new javax.swing.JPanel();
        deviceField7 = new DeviceField();
        deviceField8 = new DeviceField();
        deviceField9 = new DeviceField();
        deviceChoice3 = new DeviceChoice();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        deviceField10 = new DeviceField();
        deviceField11 = new DeviceField();
        deviceField12 = new DeviceField();
        deviceChoice4 = new DeviceChoice();
        jPanel11 = new javax.swing.JPanel();
        deviceField13 = new DeviceField();
        deviceField14 = new DeviceField();
        deviceField15 = new DeviceField();
        deviceChoice5 = new DeviceChoice();

        setDeviceProvider("spilds:8100");
        setDeviceTitle("Arduino 2 ways Multiplexer");
        setDeviceType("ARDUINO_MUX");
        setHeight(400);
        setUpdateEvent("");
        setWidth(700);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Comment:");
        deviceField1.setNumCols(25);
        deviceField1.setOffsetNid(1);
        deviceField1.setTextOnly(true);
        jPanel3.add(deviceField1);

        deviceChoice1.setChoiceItems(new String[] {"SERIAL", "TCP"});
        deviceChoice1.setIdentifier("");
        deviceChoice1.setLabelString("Mode");
        deviceChoice1.setOffsetNid(4);
        deviceChoice1.setUpdateIdentifier("");
        jPanel3.add(deviceChoice1);

        jPanel2.add(jPanel3);

        deviceField2.setIdentifier("");
        deviceField2.setLabelString("IP Address: ");
        deviceField2.setNumCols(15);
        deviceField2.setOffsetNid(2);
        deviceField2.setTextOnly(true);
        jPanel4.add(deviceField2);

        deviceField3.setIdentifier("");
        deviceField3.setLabelString("Serial Port: ");
        deviceField3.setNumCols(15);
        deviceField3.setOffsetNid(3);
        deviceField3.setTextOnly(true);
        jPanel4.add(deviceField3);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mux 1"));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        deviceField4.setIdentifier("");
        deviceField4.setLabelString("Line1:");
        deviceField4.setNumCols(4);
        deviceField4.setOffsetNid(7);
        jPanel7.add(deviceField4);

        deviceField5.setIdentifier("");
        deviceField5.setLabelString("Line 2:");
        deviceField5.setNumCols(4);
        deviceField5.setOffsetNid(8);
        jPanel7.add(deviceField5);

        deviceField6.setIdentifier("");
        deviceField6.setLabelString("Line 3");
        deviceField6.setNumCols(4);
        deviceField6.setOffsetNid(9);
        jPanel7.add(deviceField6);

        deviceChoice2.setChoiceItems(new String[] {"YES", "NO"});
        deviceChoice2.setIdentifier("");
        deviceChoice2.setLabelString("Read Back:");
        deviceChoice2.setOffsetNid(6);
        deviceChoice2.setUpdateIdentifier("");
        jPanel7.add(deviceChoice2);

        jPanel5.add(jPanel7);

        deviceField7.setIdentifier("");
        deviceField7.setLabelString("Read Line 1:");
        deviceField7.setNumCols(4);
        deviceField7.setOffsetNid(10);
        jPanel8.add(deviceField7);

        deviceField8.setIdentifier("");
        deviceField8.setLabelString("Read line 2");
        deviceField8.setNumCols(4);
        deviceField8.setOffsetNid(11);
        jPanel8.add(deviceField8);

        deviceField9.setIdentifier("");
        deviceField9.setLabelString("Read line 3");
        deviceField9.setNumCols(4);
        deviceField9.setOffsetNid(12);
        jPanel8.add(deviceField9);

        deviceChoice3.setChoiceIntValues(new int[] {0, 1, 2, 3, 4, 5, 6, 7});
        deviceChoice3.setChoiceItems(new String[] {"0", "1", "2", "3", "4", "5", "6", "7"});
        deviceChoice3.setIdentifier("");
        deviceChoice3.setLabelString("Mux select:");
        deviceChoice3.setOffsetNid(13);
        deviceChoice3.setUpdateIdentifier("");
        jPanel8.add(deviceChoice3);

        jPanel5.add(jPanel8);

        jPanel1.add(jPanel5);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Mux 2"));
        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        deviceField10.setIdentifier("");
        deviceField10.setLabelString("Line1:");
        deviceField10.setNumCols(4);
        deviceField10.setOffsetNid(17);
        jPanel10.add(deviceField10);

        deviceField11.setIdentifier("");
        deviceField11.setLabelString("Line 2:");
        deviceField11.setNumCols(4);
        deviceField11.setOffsetNid(18);
        jPanel10.add(deviceField11);

        deviceField12.setIdentifier("");
        deviceField12.setLabelString("Line 3");
        deviceField12.setNumCols(4);
        deviceField12.setOffsetNid(19);
        jPanel10.add(deviceField12);

        deviceChoice4.setChoiceItems(new String[] {"YES", "NO"});
        deviceChoice4.setIdentifier("");
        deviceChoice4.setLabelString("Read Back:");
        deviceChoice4.setOffsetNid(16);
        deviceChoice4.setUpdateIdentifier("");
        jPanel10.add(deviceChoice4);

        jPanel9.add(jPanel10);

        deviceField13.setIdentifier("");
        deviceField13.setLabelString("Read Line 1:");
        deviceField13.setNumCols(4);
        deviceField13.setOffsetNid(20);
        jPanel11.add(deviceField13);

        deviceField14.setIdentifier("");
        deviceField14.setLabelString("Read line 2");
        deviceField14.setNumCols(4);
        deviceField14.setOffsetNid(21);
        jPanel11.add(deviceField14);

        deviceField15.setIdentifier("");
        deviceField15.setLabelString("Read line 3");
        deviceField15.setNumCols(4);
        deviceField15.setOffsetNid(22);
        jPanel11.add(deviceField15);

        deviceChoice5.setChoiceIntValues(new int[] {0, 1, 2, 3, 4, 5, 6, 7});
        deviceChoice5.setChoiceItems(new String[] {"0", "1", "2", "3", "4", "5", "6", "7"});
        deviceChoice5.setIdentifier("");
        deviceChoice5.setLabelString("Mux select:");
        deviceChoice5.setOffsetNid(23);
        deviceChoice5.setUpdateIdentifier("");
        jPanel11.add(deviceChoice5);

        jPanel9.add(jPanel11);

        jPanel1.add(jPanel9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceChoice deviceChoice1;
    private DeviceChoice deviceChoice2;
    private DeviceChoice deviceChoice3;
    private DeviceChoice deviceChoice4;
    private DeviceChoice deviceChoice5;
    private DeviceField deviceField1;
    private DeviceField deviceField10;
    private DeviceField deviceField11;
    private DeviceField deviceField12;
    private DeviceField deviceField13;
    private DeviceField deviceField14;
    private DeviceField deviceField15;
    private DeviceField deviceField2;
    private DeviceField deviceField3;
    private DeviceField deviceField4;
    private DeviceField deviceField5;
    private DeviceField deviceField6;
    private DeviceField deviceField7;
    private DeviceField deviceField8;
    private DeviceField deviceField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
